server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: mircoservice-gateway-zuul-reg-exp
