security: #添加security需要添加以下的配置并在服务端引用相应的依赖spring-boot-starter-security
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetch-registry: false # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 1000 #关闭自我保护，即已关停节点不继续保留，踢出列表

